config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  post 'auth/login', to: 'authentication#authenticate'
  post 'signup', to: 'users#create'
  post 'auth/activate', to: 'authentication#activate'
  post 'auth/password_recovery_request', to: 'authentication#password_recovery_request'
  post 'auth/password_recovery_attempt', to: 'authentication#password_recovery_attempt'
  post 'auth/update_password', to: 'authentication#update_password'
  get 'auth/check_login', to: 'authentication#check_login'
  delete 'auth/logout', to: 'authentication#log_out'

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    resources :shows, only: %i[index show new create destroy]
    resources :episodes, only: [:index]
    resources :subscriptions, only: [:create]
    patch '/notification_subscriptions/', to: "notification_subscriptions#update"
    # resources :notification_subscriptions, only: [:update]
  end
  scope :admin do
    get 'panel', to: 'admin#panel'
  end
  get 'subscriptions', to: 'shows#subscriptions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <div class="alert-box">
      <%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <div class="alert-box">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/shared/_manage_shows.html.erb
  <h3>
    Current Subscriptions
  </h3>
  <div class="shows">
    <% @shows.each do |show| %>
    <div class="show">
      <%= link_to show.title, show_path(show), class: "show-title" %>
      <%= link_to "✖", show_path(show), method: :delete, class: "show-delete"%>
    </div>
    <%# raise %>
    <% end %>
  </div>
  <h3>
    Add A Show
  </h3>

  <% if @show.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @show.errors.each do |error| %>
          <% if error == :retrieve_data %>
          <li>We couldn't retrieve any data from that location. Are you sure you submitted a valid URL?</li>
          <% elsif error == :parse_data %>
          <li>We couldn't parse any podcast data from that location. Are you sure you submitted a valid URL?</li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>


  <%= simple_form_for @show do |f| %>
  <%= f.input :rss_url, label: "RSS Feed or SoundCloud Homepage" %>
  <%= f.submit "Subscribe", class: "submit" %>
  <% end %>

app/views/shared/_subscription.html.erb
<div class="subscription">
  <div class="icon-title">
    <% if show.show_img %>
      <%= image_tag show.show_img, class: "icon" %>
    <% end %>
    <%= show.title %>
  </div>
  <div><%= show.rss_url %></div>
</div>

app/views/shared/_title.html.erb
<div class="title-management-box">
  <div "title-column">
    <h4>Manage Shows</h4>
    <h4><%= current_user.email %></h5>
  </div>
  <div "logout-column">
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </div>
</div>

app/views/shared/_two_column_view.html.erb
<% cache [@episodes, @shows] do %>
<div class="main flex-between-column">
  <div class="a-block flex-around-row">
    <h1>Latest Episodes</h1>
  </div>


  <div class="b-block flex-between-column">
    <%= render partial: 'episodes/episode', collection: @episodes, cached: true %>
  </div>

  <div class="c-block flex-between-column">
    <%= render partial: 'shared/manage_shows', locals: {shows: @shows} %>
  </div>

  <div class="d-block flex-between-column">
    <div class="footer-links">
      <p>
        <%= link_to("Logout #{current_user.email}", destroy_user_session_path) %>
      </p>

      <p>
        <%= link_to "Subscribed URLs", subscriptions_path %>
      </p>
    </div>



    <p>
      Icon made by <a href="https://www.flaticon.com/authors/catkuro" title="catkuro" target="_blank">catkuro</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0.</a>
    </p>



  </div>
</div>
<!--     <div class="black"></div>
    <div class="header">
        <h4>Latest Episodes</h4>
    </div>
    <div class="logout-box">
    </div>
    <div class="main">
    </div>
    <div class="sidebar">
    </div>
    <div class="footer">
    </div>
  </div>
-->

<% end %>

app/views/shared/_url.html.erb
<div class="url">
  <div>
    <% if show.show_img %>
      <%= image_tag show.show_img %>
    <% end %>
    <%= show.title %>
  </div>
  <div><%= show.rss_url %></div>
</div>